### ISSUE TITLE
Nextcloud subpath support

### ISSUE THREAD

**Issue by robertmx** [nextcloud/whiteboard#160]
It seems that the whiteboard server or app does not support nextcloud subpath deployments. I have a nextcloud server running under https://example.com/nextcloud/*. During loading of the whiteboard I see requests to https://example.com/* which obviously can not succeed.

**Comment by juliushaertl** [comment]
Did you configure the full URL including the subpath in the as `NEXTCLOUD_URL` in the backend server deployment?

**Comment by robertmx** [comment]
Thanks for coming back to this issue. Yes I did use the full subpath.

```
# Nextcloud config (using internal docker container name)
./occ config:app:set whiteboard collabBackendUrl --value="http://nextcloud-whiteboard:3002"
./occ config:app:set whiteboard jwt_secret_key --value="{{ NEXTCLOUD_WHITEBOARD_SECRET }}"

# Whiteboard Docker env (via Ansible)
    env:
      NEXTCLOUD_URL: "https://example.com/nextcloud"
      JWT_SECRET_KEY: "{{ NEXTCLOUD_WHITEBOARD_SECRET }}"

```
