### ISSUE TITLE
On Nextcloud 29.0.0 .whiteboard files are downloaded and not opened

### ISSUE THREAD

**Issue by TobiasHofmaenner** [nextcloud/whiteboard#264]
Hey,
I'm on version 1.0.4 of whiteboard and Nextcloud 29.0.0
My config is on the server is:
```
version: '3.7'
services:
  nextcloud-whiteboard-server:
    image: ghcr.io/nextcloud-releases/whiteboard:release
    ports:
      - 3002:3002
    environment:
      - NEXTCLOUD_URL=https://cloud.mynextcloud.tld/
      - JWT_SECRET_KEY=A9CXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXWd7
```
Then to reach it I'm using a cloudflared tunnel, which handles ssl for me (https://wb.myWBserver.tld -> http://localhost:3002)
In Nextcloud I enter the credentials and get a green check mark.
When I visit https://wb.myWBserver.tld in the browser I get ```Excalidraw collaboration server is up :)```
I followed the instructions on the github page and checked the mimetype files (i don't have any entries related to whiteboards)
But it still just downloads the files.
