### ISSUE TITLE
Use Docker secrets for the JWT token

### ISSUE THREAD

**Issue by gbcreation** [nextcloud/whiteboard#394]
I use Docker Compose to run Whiteboard, and currently I define the JWT token using the `JWT_SECRET_KEY` environment variable like this:

```
version: '3.7'
services:
  nextcloud-whiteboard-server:
    image: ghcr.io/nextcloud-releases/whiteboard:release
    ports:
      - 3002:3002
    environment:
      - NEXTCLOUD_URL=https://nextcloud.local
      - JWT_SECRET_KEY=some-random-key
```

I would like to define the JWT token using Docker Secrets like this:

```
version: '3.7'
secrets:
  whiteboard_jwt_token:
    file: whiteboard_jwt_token
services:
  nextcloud-whiteboard-server:
    image: ghcr.io/nextcloud-releases/whiteboard:release
    ports:
      - 3002:3002
    secrets:
      - whiteboard_jwt_token
    environment:
      - NEXTCLOUD_URL=https://nextcloud.local
      - JWT_SECRET_KEY_FILE=/run/secrets/whiteboard_jwt_token
```

Would it be possible to implement this feature?
